server:
  port: 8082

spring:
  application:
    name: catalogo-service

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: arka
    password: arka123